### PR TITLE
#28 Updated .d.ts file to avoid exported external package typings file issues

### PR DESCRIPTION
**Pull request by cmj91uk**
This seems to sort the problem out for me. I'm not 100% sure of the full implications of making this change to the .d.ts file.

This is my first PR so if there are any issues please let me know and I can try and get them sorted out if you are happy to merge!

### CODE REVIEW

**Comment by timoxley** [comment]
@artfuldev can you please review this?

**Comment by artfuldev** [comment]
Sorry, but I think exporting modules is not the recommended way. The typescript compiler itself generates a different set of declarations. I've proposed a separate pull request #31

**Comment by cmj91uk** [comment]
Not a problem... this was based on a bit of research I did online and appeared to solve the issue.
I've tried out the changes in your separate pull request and it certainly seems to resolve the issue I originally raised when implemented locally.

**Comment by artfuldev** [comment]
@cmj91uk That's great, thanks for your feedback. :+1:  Confirms my solution as well.

**Pull request merged**
